theme: jekyll-theme-cayman
markdown: Redcarpet
description: "[Jiahe Jin](https://github.com/zizi0123)*, [Yanheng He](https://github.com/henryhe0123)*, [Mingyan Yang](https://github.com/fircube)*"
title: "Revisiting 3D LLM Benchmarks: Are We Really Testing 3D Capabilities?"
